### PR TITLE
Example nits

### PR DESCRIPTION
**Pull request by hildjj**
Makes a few tiny changes to the docs for clarity.
Updates dependencies, since I was there.

### CODE REVIEW

**Review by Mingun — APPROVED** [review]

**Comment by hildjj** [comment]
OK, i'm done fiddling with this if anyone wants to review.

**Comment by hildjj** [comment]
(sorry I added to it after your review, @Mingun)

**Review by Mingun — APPROVED** [review]
Don't worry, it just I was too fast to review it

**Comment by hildjj** [comment]
I want to resolve https://github.com/peggyjs/peggy/issues/403 before merging this.  One thing that might need to change in the docs is to add a typescript example which uses `import * as peggy from 'peggy'`

**Comment by hildjj** [comment]
I checked that TS didn't require any special effort, and that it was returning the correct types.  Tried to make it more clear that most people should be using the CLI and not the API anyway.  Found a couple of ways to configure TS that required `import * as peggy`, so added that as a hint.

**Pull request merged**
