### PR TITLE
Use generated tag in top comment

### PR DESCRIPTION
**Pull request by kristiandupont**
The `@generated` annotation is a semi-standard which is respected by a number of tools. For instance, Github detects it and skips diff's for files with it. There is also an [ESLint plugin](https://github.com/zertosh/eslint-plugin-ignore-generated) that respects it.

This PR changes the comment a tiny bit so that the annotation is included.

### CODE REVIEW

**Comment by hildjj** [comment]
Love this.  Can you add yourself to the AUTHORS file, please?

**Comment by hildjj** [comment]
Also run `npm run build`, please.  This should probably touch a few more files.

**Comment by hildjj** [comment]
Linking to https://github.com/jsdoc/jsdoc.github.io/issues/217

**Comment by kristiandupont** [comment]
Done. Let me know if there's anything else!

**Comment by hildjj** [comment]
Thanks!

**Pull request merged**
