### PR TITLE
Fixed documentation typo

### PR DESCRIPTION
**Pull request by XenoS-ITA**
in the `Importing External Rules` section, where the `--allowed-start-rules` option was being remembered there was `\*` and not *

### CODE REVIEW

**Comment by hildjj** [comment]
In many shells, if you don't escape that '*', it's going to glob-expand to all of the files in cwd.

**Comment by hildjj** [comment]
I'd settle for `'*'` as a compromise that should work most places?

**Comment by hildjj** [comment]
Also, please add yourself to the AUTHORS file and add an entry in CHANGELOG.md

**Comment by XenoS-ITA** [comment]
ok, so probably only a windows thing (the fact that it will not escape it)

when executing `npx peggy file.peggy --allowed-start-rules \*` on CMD it will prompt with: 
```
Error parsing grammar
Unknown start rule "\*"
```

**Comment by XenoS-ITA** [comment]
> I'd settle for `'*'` as a compromise that should work most places?
that doesn't work either on windows.
probably the best is to put both versions or `--allowed-start-rules * (remember the to escape it on some shells)`

**Comment by hildjj** [comment]
what happens with single quotes on windows?  windows' shell makes very strange decisions because it leaves globbing to each program to do.

**Comment by XenoS-ITA** [comment]
> what happens with single quotes on windows? windows' shell makes very strange decisions because it leaves globbing to each program to do.

same:
Error parsing grammar
Unknown start rule "'*'"

**Comment by XenoS-ITA** [comment]
What should i write in the changelog?

**Comment by hildjj** [comment]
do double quotes work?

In the changelog, put a link to this PR, and describe the change briefly.  something like "updated docs to make \`--allowedRules *\` more clear

**Pull request merged**
