### PR TITLE
Add `SyntaxErrorConstructor` type

### LINKED ISSUE #216: Using `instanceof SyntaxError` does not work with TypeScript
The following code produces an error in TypeScript:

```ts
import peggy from "peggy";

const myParser = peggy.generate(`
  Integer "integer"
    = [0-9]+
`);

try {
  myParser.parse("invalid input");
} catch (err) {
  // ERROR: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.ts(2359)
  if (err instanceof myParser.SyntaxError) {
    console.log("It is a SyntaxError");
  }
}
```
(https://codesandbox.io/s/xenodochial-liskov-kmcyk?file=/src/index.ts)

The code reaches the `console.log` statement, i.e. the JS runs correctly. However, Typescript complains that I cannot use `myParser.SyntaxError` on the right hand side of the `instanceof` check. I tried to investigate this, but couldn't figure out why it happens. Something must be wrong with the type definitions (tested on TypeScript `4.4.4`).

### PR DESCRIPTION
**Pull request by cmfcmf**
This fixes #216 by introducing a new `SyntaxErrorConstructor` type. This is similar to how other classes are typed in Typescript, e.g. https://github.com/microsoft/TypeScript/blob/0163a624b7d91a29cf24b4d411fd6d52fb5339cb/lib/lib.es5.d.ts#L1594-L1599

### CODE REVIEW

**Review by phpnode — APPROVED** [review]

**Comment by hildjj** [comment]
Can you please rebase this on the 1.3 branch, and ensure that the PR is relative to that branch?

**Comment by cmfcmf** [comment]
Done!

**Comment by hildjj** [comment]
Thank you.  Good type test!

**Comment by hildjj** [comment]
@cmfcmf can you also add yourself to the AUTHORS file in a new PR, please?  I should have asked for that before merging.

**Comment by cmfcmf** [comment]
> @cmfcmf can you also add yourself to the AUTHORS file in a new PR, please? I should have asked for that before merging.

No worries! I should've read the `CONTRIBUTING.md` file more carefully I guess :D

**Pull request merged**
