### PR TITLE
Removing AUTHORS file

### PR DESCRIPTION
**Pull request by AndrewRayCode**
An AUTHORS file is similar to having a `* @author` Javadoc. It's fallen out of favor, and this information is captured in the Readme, Github history, and Github Contributors sidebar. The AUTHORS file is redundant and outdated.

### CODE REVIEW

**Comment by hildjj** [comment]
Not unless you think about the copyright notices that references the AUTHORS file, and make sure that people get called out in the package.json file as well.

I'm skeptical that this is worth any time or effort.

**Comment by AndrewRayCode** [comment]
> Not unless you think about the copyright notices that references the AUTHORS

I see `LICENSE` use the word "AUTHORS," it's unclear to me how that relates to this file. 

> make sure that people get called out in the package.json file as well.

Is this related to removing AUTHORS? Only the original peg.js author is referenced in package.json.
 
> I'm skeptical that this is worth any time or effort.

Up to you! `AUTHORS` is objectively redundant, and there's no hygiene on it, namely no one enforces contributors are in this file, so I don't think it has any value.

**Comment by hildjj** [comment]
I did a pretty thorough pass to ensure AUTHORS was up-to-date when I took over maintenance.  After that, I've tried to be careful to get new contributors to add themselves there as well.  If someone forked this project and removed my name from it, citing that my contributions were available in the github history, I'd be miffed.  Therefore, I don't want to do that to others.

I'll leave this open for another day in case there are other opinions or arguments to be made.

**Comment by AndrewRayCode** [comment]
It sounds like you have decided 😃 it is up to you, I don’t mind if you close. Having fewer open issues and PRs makes it easier for new contributors

**Comment by hildjj** [comment]
Seeing no other comments, I am going to close this.

**Pull request closed without merging**
