### PR TITLE
Website: show errors in editors

### PR DESCRIPTION
**Pull request by Mingun**
firefox_GhQu106spX

### CODE REVIEW

**Comment by hildjj** [comment]
I like this.  We should also update everything else in docs/vendor/codemirror in this PR.

**Comment by hildjj** [comment]
> We should also update everything else in docs/vendor/codemirror in this PR.

See #48 for discussion.

**Comment by Mingun** [comment]
Do you mean updating to CodeMirror 6? I probably cannot do that, because my web kung-fu is very limited and the editor was significantly rewritten.

**Comment by hildjj** [comment]
I did, but then I looked at it, and they sure managed to make Codemirror harder to get started with.  Let's make sure we've got the latest build of CodeMirror5, then open a new ticket for moving to CodeMirror6, with the "Help Requested" tag.  Maybe someone will pitch in.

**Comment by hildjj** [comment]
Of course, updating to CodeMirror 5.65.5 didn't "just work" either.  Let's take this as-is.  I'll open the CM6 bug as well.

**Pull request merged**
