### PR TITLE
Visually improve announce

### LINKED ISSUE #138: More visible section headings in build path
Just making it a little easier to read what's going on.  This PR introduces the blue and white coloring in the headings.

This still looks good on a black and white terminal.

image

### PR DESCRIPTION
**Pull request by StoneCypher**
Just making it a little easier to read what's going on.  This PR introduces the blue and white coloring in the headings.

This still looks good on a black and white terminal.

This is a single file change, and will significantly shrink when #107 lands.

image

Fixes #138

### CODE REVIEW

**Comment by hildjj** [comment]
We're getting pretty close to the functionality of [boxen](https://www.npmjs.com/package/boxen) here.  Why not just take a dev dependency?

**Comment by hildjj** [comment]
Or just take [boxen-cli](https://github.com/sindresorhus/boxen-cli) and replace our announce script.

**Comment by StoneCypher** [comment]
> We're getting pretty close to the functionality of boxen here. Why not just take a dev dependency?

Because the work is already done, and there's no purpose in doing it again.  Because Boxen is ugly, and the thing you want to replace was already in there; all I did was add color.

Because switching to Boxen is actually a lot more work than you think it is.  This means re-figuring all of the 

Because we don't know the portability or quality of Boxen.

Because Boxen doesn't actually add anything of value here.

This is all

**Comment by StoneCypher** [comment]
> We're getting pretty close to the functionality of boxen here. Why not just take a dev dependency?

Because this is tables, and Boxen doesn't appear to do tables.  This cannot actually be used to do this job.

***Because the work is already done, and there's no purpose in doing it again.  Requesting someone re-do something they already did is not productive, and is becoming a repeat pattern with this team.***

Because Boxen is ugly, and the thing you want to replace was already in the script; this wasn't added.  All I did was colorize.

Because switching to Boxen is actually a lot more work than you think it is.  This means re-figuring all of the layout stuff.

Because we don't know the portability or quality of Boxen.

Because Boxen doesn't actually add anything of value here.

Because Boxen can't represent this, because it doesn't do background colors.

Because this still needs to exist for the row coloring.

Because Boxen can't do intermediate borders.

Because this is all coming out when we switch to Artillery anyway.

**Comment by StoneCypher** [comment]
If you're going to suggest that someone replace work they already did, please:

1. Make sure your replacement can actually do the job
2. Have a good reason they should do the work a second time
3. Recognize the emotional impact of making people fight for trivial things

**Comment by hildjj** [comment]
I'm just talking about the announce script, which is what this PR is about.  It's a few lines of code, so I didn't think you'd feel this strongly about it.  I apologize.

**Comment by StoneCypher** [comment]
> I'm just talking about the announce script, which is what this PR is about. It's a few lines of code, so I didn't think you'd feel this strongly about it. I apologize.

I don't.

What I feel strongly about is that a valuable PR is several days blocked because we won't stop arguing about meaningless things and just get the work in.

If you want to switch to boxen, the correct step is to merge the PR, then do that yourself and put it up for discussion, not request that of someone else and toss the thing they already did.

Most people really don't like re-doing work because someone else had an idea on the spot.  It trivializes their contributions to being worth less than someone's curious notion.

It has nothing to do with the suggestion; I just answered your question.  

"Why don't we do it this other way?"

Because this is already done.  Cut it out.  That the other way doesn't work is more just frustrating because you didn't think it through before suggesting someone start over. 

That is a big red emotional button.  It should only be used when it's necessary.

I am trying to de-normalize your use of it.

**Comment by StoneCypher** [comment]
Please explain why this PR is closed, @hildjj

**Pull request closed without merging**
