### PR TITLE
Move from travis to gh-actions

### PR DESCRIPTION
**Pull request by hildjj**
Fixup babelify in the process

### CODE REVIEW

**Comment by GreenImp** [comment]
Genuinely interested; what was the reason for moving to Github actions, instead of Travis?
I'm using Travis on some libraries myself, and haven't have any issues, but haven't used GitHub actions before.

**Comment by phpnode** [comment]
Travis has been bought by a private equity firm and has massively restricted and reduced the performance of their free tier unfortunately

**Comment by GreenImp** [comment]
Oh really? I hadn't heard about that!

Just found an article that sums it up nicely: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
And Travis' blog about the changes: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing#building-on-a-public-repositories-only

That's a real shame; they used to be really good for Open Source stuff. I guess I'll have to swap over my own repos to Github actions as well then.

Thanks for taking the time to get back to me.

**Comment by hildjj** [comment]
In addition, I have too many repos to be able to use the tools Travis provided to move from .org to .com, and their command line tool didn't do an adequate job.  I've been using GH Actions for a while now on a few other projects, and I like it a lot, aside from it not having the feature that allows a checkin to be marked `[skip ci]`.  I'm not paying for the CPU, and none of my projects are Firefox-sized, so it hasn't been an issue.

**Pull request merged**
