### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by hildjj**
Depends on https://github.com/peggyjs/peggyjs-eslint-config/pull/3

This is the needed changes in response to the new lint rules.
I will not merge this without a full plan in place.

### CODE REVIEW

**Comment by hildjj** [comment]
note that the tests for this won't pass until `@peggyjs/eslint-config` is updated.

**Comment by hildjj** [comment]
OK, this is ready to go.  The `linebreak-style` rule flagged our line endings on Windows, which I've now fixed in my preferred style (force line endings to LF everywhere for the file types that support that).  I'm pausing for a moment before merging in case anyone has an opinion about that.

**Comment by Mingun** [comment]
`linebreak-style` probably could be a little problem... Maybe disable this and instead use git abilities to automatically convert all to LF when commit. According to [the manual](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf), `core.autocrlf` setting can handle all that stuff in a great way. This setting is on be default in TortoiseGit (I think this is the most powerful git client and most convenient at all and used by most Windows users, including me)

**Comment by hildjj** [comment]
My assumption is that LF works fine on Windows for all of the file types listed in the `.gitattributes` file.  As such, I wanted the CI done on LF-ended files, so that we could do checksums if we wanted to one day.

Granted, I don't do dev work on Windows, so I don't know if all editors that are not vscode will work adequately without CRLF encoding.  If it's much more comfortable to work in CRLF, then you way is probably fine.  It's the default, so I would just remove the .gitattributes file and remove the lint rule.

**Comment by Mingun** [comment]
On the other hand, having `.gitattributes` should normalize working copy. Strange, why git didn't do that when I checkout your branch, it seems it should have done this. Even `git reset --hard` didn't help, so I've changed all endings manually. I"m OK with that now.

**Comment by hildjj** [comment]
Sorry, just to be clear, you're ok with my merging this PR as-is, right?

**Comment by hildjj** [comment]
also I found `git add --renormalize .` fixed everything up.

**Comment by Mingun** [comment]
Yes, initially I didn't understood that `.gitattributes` should handle all things right, because git didn't convert my existing working copy. But fresh checkout should be ended with the LF endings. So merge it as-is please.

**Pull request merged**
