### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by hildjj**
Issues fixed:
- Jest thinks the sourcemap URL writing code is a sourcemap for the target file.  Symptom: "Test suite failed to run at invariant"
- Update to commander added the `error` method, as requested.  No longer need to use internal API.
- Ensured that run.spec.ts more-or-less passes conversion to JS with tsc
- On node 18, SourceMapConsumer was failing because `fetch` now exists.  Updated to latest beta of source-map to get around this issue

### CODE REVIEW

**Comment by hildjj** [comment]
And of course the latest Jest doesn't support node 10 anymore.  I can either go back to a working version, or we can deprecate node 10.  Opinions?

**Comment by hildjj** [comment]
Trying to back down to jest 27.5.1 isn't working terribly well.  There are still several other deps that don't support node 10 anymore.

I think it may be time to drop node 10 support.  Should we do a major version change for that?

**Comment by smcjones** [comment]
Not a regular contributor here, but voting to add a major version change for deprecation. It'll be easier to track the nest of node dependencies.

**Comment by hildjj** [comment]
@smcjones 's argument is persuasive.  If we do cut this as a 2.0 release, I think I'll want to be more aggressive about #223, moving to a more-normal dependency relationship instead of bundling.

**Comment by Mingun** [comment]
It seems that according to semver dropping support of old environment should be a breaking change that requires major version bump. Relevant discussion: https://github.com/semver/semver/issues/317

**Pull request merged**
