### PR TITLE
Fix broken indentation of some codeblocks

### PR DESCRIPTION
**Pull request by Mingun**
Commit 2691644664c60daa7cbf10de30bb4a9f4722750f from #313 has broken some indentation, and my own PR #291 mention the wrong version number since that the repetition operator is available, so I've fixed both problems.

### CODE REVIEW

**Comment by hildjj** [comment]
Sorry that I was sloppy when fixing those up.  Once I noticed that there were some wrong, I should have checked all of them.

This also needs to land on stable.  I guess I cherry-pick this onto my local stable branch, then do a PR where the target is stable?

**Comment by Mingun** [comment]
As you wish. Honestly, I managed to forget the workflow that you want to adhere to. Interestingly, when I had making this PR, GitHub reported some strange create PR url which in fact was a compare form instead of a PR making form.

**Comment by hildjj** [comment]
According to https://stackoverflow.com/questions/45169565/git-applying-changes-to-two-branches, I think the right way to land this is to have this PR be against the `docs-feature` branch, which I just created.  Then we can merge that branch to stable and to main.

**Comment by hildjj** [comment]
I tried resetting the base, but that didn't work cleanly, because it still picked up the CHANGELOG.md change that I want to leave on `main`.  I think you'll need to rebase on your side first.

**Comment by Mingun** [comment]
Done

**Comment by hildjj** [comment]
Merged to stable and main.  Published to site.  Found #352 in the process.

**Pull request merged**
